source 'https://cdn.cocoapods.org/'
source 'https://github.com/tedke7-vecpuj-riFzij/scdatasdk-specs.git'

use_frameworks!

platform :ios, '10.0'

target 'SCDataSDK_O_Example' do
  pod 'SCDataSDK_O', :path => '../'
#  pod 'SCDataSDK_O'

  target 'SCDataSDK_O_Tests' do
    inherit! :search_paths

  end
end
