#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.0 effective-4.1.50 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)
#ifndef SCDATASDK_SWIFT_H
#define SCDATASDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="SCDataSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

/// 基础事件
SWIFT_CLASS("_TtC9SCDataSDK11SCDataEvent")
@interface SCDataEvent : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSString;

/// 页面访问事件
SWIFT_CLASS("_TtC9SCDataSDK21SCDataAccessPageEvent")
@interface SCDataAccessPageEvent : SCDataEvent
/// 访问类型
/// 1 前台访问， 2 后台访问
@property (nonatomic) NSInteger operateType;
/// 页面名称（首页、专题等）
@property (nonatomic, copy) NSString * _Nonnull sourceName;
/// 页面id（新闻、直播等id）
@property (nonatomic, copy) NSString * _Nonnull sourceId;
/// 进入类型
/// 0 进入 ，1 退出
@property (nonatomic) NSInteger action;
/// 访问时长，单位秒
@property (nonatomic) NSInteger timeLength;
/// 是否是首页
/// 0: 不是 ，1: 是
@property (nonatomic) NSInteger isHome;
/// 页面类型
/// 0 新闻点播（视频）， 1 专题， 2 直播/频道（互动直播），3、电视直播4、资讯（稿件） 5、广播电台  6、爆料 7、问政 8、积分商城  9、微头条、10社交、11、广告 12 其他
@property (nonatomic) NSInteger sourceType;
/// 页面路径
/// 进入页面ID，从A页面跳转到当前页面B，这个地方填A的ID，如果没有则空
@property (nonatomic, copy) NSString * _Nonnull sourcePage;
/// 所属栏目id
@property (nonatomic, copy) NSString * _Nonnull pChannel;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// 资源访问事件
SWIFT_CLASS("_TtC9SCDataSDK23SCDataAccessSourceEvent")
@interface SCDataAccessSourceEvent : SCDataEvent
/// 资源id，新闻稿件id（新闻或者直播等能取到时必传）
@property (nonatomic, copy) NSString * _Nonnull sourceId;
/// 文章摘要
@property (nonatomic, copy) NSString * _Nonnull summary;
/// 退出事件，格式时间戳
@property (nonatomic, copy) NSString * _Nonnull offtime;
/// 资源路径
@property (nonatomic, copy) NSString * _Nonnull path;
/// 访问时长，单位秒
@property (nonatomic) NSInteger timeLength;
/// 资源类型
/// 0 新闻点播（视频）， 1 专题， 2 直播/频道（互动直播），3、电视直播4、资讯（稿件） 5、广播电台  6、爆料 7、问政 8、积分商城  9、微头条、10社交、11、广告 12 其他
@property (nonatomic) NSInteger sourceType;
/// 页面打开或者退出
/// 0 进入，1退出
@property (nonatomic) NSInteger action;
/// 标题（新闻或直播等能取到时必传）
@property (nonatomic, copy) NSString * _Nonnull sourceName;
/// 新闻标签（频道/栏目信息）
@property (nonatomic, copy) NSString * _Nonnull sourceTag;
/// 频道/栏目id
@property (nonatomic, copy) NSString * _Nonnull channelId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// 基础信息事件
SWIFT_CLASS("_TtC9SCDataSDK20SCDataBasicInfoEvent")
@interface SCDataBasicInfoEvent : SCDataEvent
/// idfa
@property (nonatomic, copy) NSString * _Nonnull idfa;
/// 用户性别
/// 0 男、1 女
@property (nonatomic) NSInteger sex;
/// 用户年龄
@property (nonatomic) NSInteger age;
/// 用户手机号
@property (nonatomic, copy) NSString * _Nonnull phoneNumber;
/// 手机型号代码
@property (nonatomic, copy) NSString * _Nonnull phoneType;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// 爆料发布事件
SWIFT_CLASS("_TtC9SCDataSDK20SCDataBrokeNewsEvent")
@interface SCDataBrokeNewsEvent : SCDataEvent
/// 发布内容id，如动态id
@property (nonatomic, copy) NSString * _Nonnull sourceId;
/// 爆料内容
@property (nonatomic, copy) NSString * _Nonnull sourceContent;
/// 爆料内容标题
@property (nonatomic, copy) NSString * _Nonnull blTitle;
/// 资源类型
/// 0 新闻点播（视频）， 1 专题， 2 直播/频道（互动直播），3、电视直播4、资讯（稿件） 5、广播电台  6、爆料 7、问政 8、积分商城  9、微头条、10社交、11、广告 12 其他
@property (nonatomic) NSInteger sourceType;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// 收藏事件
SWIFT_CLASS("_TtC9SCDataSDK18SCDataCollectEvent")
@interface SCDataCollectEvent : SCDataEvent
/// 资源id，新闻或者直播id
@property (nonatomic, copy) NSString * _Nonnull sourceId;
/// 资源名称，新闻、直播等标题
@property (nonatomic, copy) NSString * _Nonnull sourceName;
/// 操作类型
/// 收藏为true，取消收藏为false
@property (nonatomic) BOOL operationType;
/// 资源类型
/// 0 新闻点播（视频）， 1 专题， 2 直播/频道（互动直播），3、电视直播4、资讯（稿件） 5、广播电台  6、爆料 7、问政 8、积分商城  9、微头条、10社交、11、广告 12 其他
@property (nonatomic) NSInteger sourceType;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// 评论事件
SWIFT_CLASS("_TtC9SCDataSDK18SCDataCommentEvent")
@interface SCDataCommentEvent : SCDataEvent
/// 资源名称，新闻、直播等标题
@property (nonatomic, copy) NSString * _Nonnull sourceName;
/// 资源id，新闻或者直播id
@property (nonatomic, copy) NSString * _Nonnull sourceId;
/// 评论内容
@property (nonatomic, copy) NSString * _Nonnull commentDetail;
/// 资源类型
/// 0 新闻点播（视频）， 1 专题， 2 直播/频道（互动直播），3、电视直播4、资讯（稿件） 5、广播电台  6、爆料 7、问政 8、积分商城  9、微头条、10社交、11、广告 12 其他
@property (nonatomic) NSInteger sourceType;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




/// 分享、转发事件
SWIFT_CLASS("_TtC9SCDataSDK18SCDataForwardEvent")
@interface SCDataForwardEvent : SCDataEvent
/// 资源名称，新闻、直播等标题
@property (nonatomic, copy) NSString * _Nonnull sourceName;
/// 资源id，新闻或者直播id
@property (nonatomic, copy) NSString * _Nonnull sourceId;
/// 资源类型
/// 0 新闻点播（视频）， 1 专题， 2 直播/频道（互动直播），3、电视直播4、资讯（稿件） 5、广播电台  6、爆料 7、问政 8、积分商城  9、微头条、10社交、11、广告 12 其他
@property (nonatomic) NSInteger sourceType;
/// 分享渠道
/// 0 微信、1 微博、 2 qq、3 其他
@property (nonatomic) NSInteger channelId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// 直播、电视、电视台相关事件
SWIFT_CLASS("_TtC9SCDataSDK15SCDataLiveEvent")
@interface SCDataLiveEvent : SCDataEvent
/// 资源名称，新闻、直播等标题
@property (nonatomic, copy) NSString * _Nonnull sourceName;
/// 资源id，新闻或者直播id
@property (nonatomic, copy) NSString * _Nonnull sourceId;
/// 心跳时间：第一次开启直播统计直播事件时心跳值为0，之后每次调用值为60；
/// 即每隔60秒上传一次直播日志
@property (nonatomic) NSInteger heartbeatLength;
/// 1、普通直播 2、互动直播、3、电台直播、4、电视直播、5、慢直播
@property (nonatomic) NSInteger liveType;
/// 退出时间，格式时间戳，退出类型的时候使用
@property (nonatomic, copy) NSString * _Nonnull offtime;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// 定位信息
SWIFT_CLASS("_TtC9SCDataSDK14SCDataLocation")
@interface SCDataLocation : NSObject
/// 定位信息初始化
/// \param latitude 经度
///
/// \param longitude 纬度
///
- (nonnull instancetype)initWithLatitude:(NSString * _Nonnull)latitude longitude:(NSString * _Nonnull)longitude OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


/// 登录事件
SWIFT_CLASS("_TtC9SCDataSDK16SCDataLoginEvent")
@interface SCDataLoginEvent : SCDataEvent
/// 用户id，有手机号传手机号，否则传用户id，未登录传空字
@property (nonatomic, copy) NSString * _Nonnull userId;
/// 登录事件
/// 登入传1，退出传2
@property (nonatomic) NSInteger operateType;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// 点赞事件
SWIFT_CLASS("_TtC9SCDataSDK17SCDataPraiseEvent")
@interface SCDataPraiseEvent : SCDataEvent
/// 资源名称，新闻、直播等标题
@property (nonatomic, copy) NSString * _Nonnull sourceName;
/// 资源id，新闻或者直播id
@property (nonatomic, copy) NSString * _Nonnull sourceId;
/// 资源类型
/// 0 新闻点播（视频）， 1 专题， 2 直播/频道（互动直播），3、电视直播4、资讯（稿件） 5、广播电台  6、爆料 7、问政 8、积分商城  9、微头条、10社交、11、广告 12 其他
@property (nonatomic) NSInteger sourceType;
/// 1、点赞  2、取消点赞
@property (nonatomic) NSInteger operationType;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// 推送事件
SWIFT_CLASS("_TtC9SCDataSDK15SCDataPushEvent")
@interface SCDataPushEvent : SCDataEvent
/// 推送id
@property (nonatomic, copy) NSString * _Nonnull sourceId;
/// 资源类型
/// 0 新闻点播（视频）， 1 专题， 2 直播/频道（互动直播），3、电视直播4、资讯（稿件） 5、广播电台  6、爆料 7、问政 8、积分商城  9、微头条、10社交、11、广告 12 其他
@property (nonatomic) NSInteger sourceType;
/// 推送标题
@property (nonatomic, copy) NSString * _Nonnull sourceName;
/// 操作类型，1 收到推送 2 打开推送
@property (nonatomic) NSInteger operateType;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// 搜索事件
SWIFT_CLASS("_TtC9SCDataSDK17SCDataSearchEvent")
@interface SCDataSearchEvent : SCDataEvent
/// 搜索内容
@property (nonatomic, copy) NSString * _Nonnull content;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9SCDataSDK13SCDataService")
@interface SCDataService : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
/// 初始化统计服务
/// \param areaId 区域id，组织机构唯一上报标识。
///
/// \param token 授权token
///
/// \param usertId 用户id或者电话号码
///
/// \param latitude 经度
///
/// \param longtitude 纬度
///
/// \param logEnable 是否开启日志打印
///
///
/// returns:
/// 初始化是否成功
+ (BOOL)registerAppWithAreaId:(NSString * _Nonnull)areaId token:(NSString * _Nonnull)token userId:(NSString * _Nonnull)userId latitude:(NSString * _Nonnull)latitude longtitude:(NSString * _Nonnull)longtitude logEnable:(BOOL)logEnable;
/// 获取SDK版本号
///
/// returns:
/// 当前版本
+ (NSString * _Nonnull)currentVersion SWIFT_WARN_UNUSED_RESULT;
/// 埋点
/// \param event 各点位事件
///
/// \param immediately 是否立即上传，默认不会立即上传，埋点数据达到20条后会自动上传。
///
+ (void)trackEvent:(SCDataEvent * _Nonnull)event immediately:(BOOL)immediately;
/// 设置定位信息
/// \param location 定位信息
///
+ (void)setLocationWithLocation:(SCDataLocation * _Nonnull)location;
@end



/// 视频播放事件
SWIFT_CLASS("_TtC9SCDataSDK20SCDataVideoPlayEvent")
@interface SCDataVideoPlayEvent : SCDataEvent
/// 资源名称，新闻、直播等标题
@property (nonatomic, copy) NSString * _Nonnull sourceName;
/// 资源id，新闻或者直播id
@property (nonatomic, copy) NSString * _Nonnull sourceId;
/// 视频时长（单位：秒）
@property (nonatomic) NSInteger contentLength;
/// 是否播放完成
/// true 已看完 , false 未看完
@property (nonatomic) BOOL isComplete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
